pipeline {
    // agent {
    //     docker {
    //         image 'maven:3.9.0'
    //         args '-v /root/.m2:/root/.m2'
    //     }
    // }
          tools {
    maven 'maven' 
  }
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                // sh 'ls -laR target'
                sh "chmod +x -R ${env.WORKSPACE}"
                
                withCredentials([sshUserPrivateKey(credentialsId: "tomcat", keyFileVariable: 'KEYFILE')]) {
                    sh 'ssh -i $KEYFILE dhluser@10.0.0.5 uname -a'
                    sh './jenkins/scripts/deliver.sh $KEYFILE $BUILD_NUMBER'
                    sh './jenkins/scripts/copy.sh $KEYFILE'
                }

                // sshagent(credentials : ['tomcat']) {
                //     sh 'ssh -o StrictHostKeyChecking=no dhluser@10.0.0.5 uptime'
                //     sh 'ssh -o StrictHostKeyChecking=no dhluser@10.0.0.5 ls /opt/tomcat/webapps'
                //     sh 'ssh -v dhluser@10.0.0.5'
                //     //sh 'scp ./source/filename user@hostname.com:/remotehost/target'
        }
    //             def remote = [:]
    // remote.name = 'test'
    // remote.host = 'test.domain.com'
    // remote.user = 'dhluser'
    // remote.password = 'password'
    // remote.allowAnyHosts = true
    // stage('Remote SSH') {
    //   writeFile file: 'abc.sh', text: 'ls -lrt'
    //   sshPut remote: remote, from: 'abc.sh', into: '.'
    // }
            }
        }
    }

